export const SPORTS_LIST_REQUEST = 'SPORTS_LIST_REQUEST';
export const SPORTS_LIST_SUCCESS = 'SPORTS_LIST_SUCCESS';
export const SPORTS_LIST_FAIL = 'SPORTS_LIST_FAIL';

export const SPORTS_DETAILS_REQUEST = 'SPORTS_DETAILS_REQUEST';
export const SPORTS_DETAILS_SUCCESS = 'SPORTS_DETAILS_SUCCESS';
export const SPORTS_DETAILS_FAIL = 'SPORTS_DETAILS_FAIL';

export const SPORTS_DELETE_REQUEST = 'SPORTS_DELETE_REQUEST';
export const SPORTS_DELETE_SUCCESS = 'SPORTS_DELETE_SUCCESS';
export const SPORTS_DELETE_FAIL = 'SPORTS_DELETE_FAIL';

export const SPORTS_CREATE_REQUEST = 'SPORTS_CREATE_REQUEST';
export const SPORTS_CREATE_SUCCESS = 'SPORTS_CREATE_SUCCESS';
export const SPORTS_CREATE_FAIL = 'SPORTS_CREATE_FAIL';
export const SPORTS_CREATE_RESET = 'SPORTS_CREATE_RESET';

export const SPORTS_UPDATE_REQUEST = 'SPORTS_UPDATE_REQUEST';
export const SPORTS_UPDATE_SUCCESS = 'SPORTS_UPDATE_SUCCESS';
export const SPORTS_UPDATE_FAIL = 'SPORTS_UPDATE_FAIL';
export const SPORTS_UPDATE_RESET = 'SPORTS_UPDATE_RESET';

export const SPORTS_CREATE_REVIEW_REQUEST = 'SPORTS_CREATE_REVIEW_REQUEST';
export const SPORTS_CREATE_REVIEW_SUCCESS = 'SPORTS_CREATE_REVIEW_SUCCESS';
export const SPORTS_CREATE_REVIEW_FAIL = 'SPORTS_CREATE_REVIEW_FAIL';
export const SPORTS_CREATE_REVIEW_RESET = 'SPORTS_CREATE_REVIEW_RESET';

export const SPORTS_TOP_REQUEST = 'SPORTS_TOP_REQUEST';
export const SPORTS_TOP_SUCCESS = 'SPORTS_TOP_SUCCESS';
export const SPORTS_TOP_FAIL = 'SPORTS_TOP_FAIL';
